export type NodusIaAgentStatus = 'active' | 'coming_soon' | 'disabled' | 'hidden';

export type NodusIaAgentCatalogItem = {
  id: string;
  agentKey: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: string;
  automationType: string;
  useCase: string;
  functionalities: string[];
  benefits: string[];
  inputs: string[];
  outputs: string[];
  status: NodusIaAgentStatus;
  visibleToBuyer: boolean;
  sortOrder: number;
  isActive: boolean;
  accentColor: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
};

export const nodusIaAgents: NodusIaAgentCatalogItem[] = [
  {
    id: 'terms_of_reference',
    agentKey: 'terms_of_reference',
    slug: 'elaboracion-terminos-referencia',
    name: 'Elaboracion de terminos de referencia',
    description: 'Redacta terminos de referencia claros y bien estructurados para procesos de compra y contratacion.',
    longDescription: 'Ayuda a construir TdR a partir del objetivo, alcance y entregables de la necesidad.',
    category: 'Compras',
    automationType: 'Generacion',
    useCase: 'Preparar bases documentales para servicios, consultorias, licitaciones y compras tecnicas.',
    functionalities: ['Estructura objetivo, alcance y entregables', 'Propone secciones minimas requeridas', 'Genera borrador listo para revision'],
    benefits: ['Reduce tiempo de redaccion', 'Mejora consistencia documental', 'Facilita coordinacion con usuarios internos'],
    inputs: ['Objetivo de la contratacion', 'Alcance', 'Entregables esperados', 'Documentos de apoyo'],
    outputs: ['Borrador de TdR', 'Criterios sugeridos', 'Estructura documental', 'PDF descargable'],
    status: 'active',
    visibleToBuyer: true,
    sortOrder: 1,
    isActive: true,
    accentColor: '#2563eb',
    icon: 'FileCheck',
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z',
  },
  {
    id: 'proposal_comparison',
    agentKey: 'proposal_comparison',
    slug: 'comparativos-propuestas-proveedores',
    name: 'Comparativos de propuestas de proveedores',
    description: 'Sube propuestas de proveedores y recibe una tabla comparativa con condiciones, riesgos, ranking y recomendacion final.',
    longDescription: 'Centraliza propuestas comerciales, analiza diferencias clave y genera un comparativo orientado a decision.',
    category: 'Compras',
    automationType: 'Evaluacion',
    useCase: 'Comparar propuestas en procesos de compra y sustentar la recomendacion de adjudicacion.',
    functionalities: ['Consolida propuestas y anexos', 'Ordena diferencias por precio, plazo y condiciones', 'Genera comparativo ejecutivo listo para compartir'],
    benefits: ['Acelera decisiones de compra', 'Reduce sesgos al evaluar propuestas', 'Mejora trazabilidad para auditoria interna'],
    inputs: ['Archivos de propuestas', 'Servicio o categoria', 'Objetivo del analisis'],
    outputs: ['Tabla comparativa', 'Ranking recomendado', 'Resumen ejecutivo', 'Recomendacion final', 'PDF descargable'],
    status: 'active',
    visibleToBuyer: true,
    sortOrder: 2,
    isActive: true,
    accentColor: '#0f766e',
    icon: 'Scale',
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
  {
    id: 'tco_analysis',
    agentKey: 'tco_analysis',
    slug: 'analisis-costo-total-tco',
    name: 'Analisis de Costo Total / TCO',
    description: 'Calcula el costo total real de una compra considerando precio inicial, instalacion, transporte, mantenimiento, operacion, garantia, soporte, repuestos, riesgos y costos ocultos.',
    longDescription: 'Compara alternativas por proveedor con una mirada de costo total para evitar decisiones basadas solo en precio inicial.',
    category: 'Finanzas',
    automationType: 'Analitica',
    useCase: 'Evaluar compras con impacto de largo plazo y sustentar una recomendacion TCO.',
    functionalities: ['Calcula costo inicial vs costo total proyectado', 'Detecta costos ocultos y supuestos criticos', 'Compara alternativas por proveedor', 'Genera recomendacion basada en TCO'],
    benefits: ['Evita elegir solo por precio inicial', 'Mejora decisiones de compra a largo plazo', 'Ayuda a justificar la recomendacion ante gerencia'],
    inputs: ['Alternativas por proveedor', 'Costos iniciales', 'Costos operativos', 'Horizonte de evaluacion'],
    outputs: ['Tabla TCO por proveedor', 'Costo total proyectado', 'Riesgos financieros', 'Recomendacion final', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 3,
    isActive: false,
    accentColor: '#0369a1',
    icon: 'TrendingUp',
    createdAt: '2026-04-03T00:00:00.000Z',
    updatedAt: '2026-04-03T00:00:00.000Z',
  },
  {
    id: 'purchase_order',
    agentKey: 'purchase_order',
    slug: 'elaboracion-orden-compra',
    name: 'Elaboracion de Orden de Compra',
    description: 'Genera una orden de compra formal a partir del proveedor seleccionado, condiciones comerciales, items, cantidades, precios, impuestos, entrega y observaciones.',
    longDescription: 'Estructura una orden lista para revision administrativa, con totales y condiciones comerciales ordenadas.',
    category: 'Compras',
    automationType: 'Generacion',
    useCase: 'Formalizar una compra aprobada con una orden estructurada y descargable.',
    functionalities: ['Estructura datos de proveedor y comprador', 'Genera tabla de items', 'Calcula subtotal, impuestos y total', 'Ordena condiciones comerciales'],
    benefits: ['Reduce errores administrativos', 'Estandariza ordenes de compra', 'Acelera la formalizacion de la compra'],
    inputs: ['Proveedor seleccionado', 'Items', 'Cantidades', 'Precios', 'Impuestos', 'Entrega'],
    outputs: ['Orden de compra estructurada', 'Tabla de items', 'Totales', 'Condiciones de pago y entrega', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 4,
    isActive: false,
    accentColor: '#0f766e',
    icon: 'FileCheck',
    createdAt: '2026-04-04T00:00:00.000Z',
    updatedAt: '2026-04-04T00:00:00.000Z',
  },
  {
    id: 'dashboard_creator',
    agentKey: 'dashboard_creator',
    slug: 'creador-dashboard',
    name: 'Creador de Dashboard',
    description: 'Crea un dashboard visual a partir de datos de compras, gastos, proveedores o indicadores cargados por el comprador, identificando KPIs, graficos, tablas e insights relevantes.',
    longDescription: 'Convierte datos subidos por el comprador en una estructura de dashboard con KPIs, tablas, graficos simples, insights y recomendaciones.',
    category: 'Reporteria',
    automationType: 'Analitica',
    useCase: 'Crear una vista ejecutiva inicial a partir de datos de compras o proveedores.',
    functionalities: ['Lee archivos de datos', 'Propone KPIs', 'Genera estructura de dashboard', 'Crea tablas y graficos visuales en la plataforma', 'Detecta insights relevantes'],
    benefits: ['Convierte datos en visualizaciones utiles', 'Ayuda a presentar resultados a gerencia', 'Reduce trabajo manual en Excel o Power BI inicial'],
    inputs: ['Archivo de datos', 'Objetivo del dashboard', 'Audiencia', 'Periodo'],
    outputs: ['Dashboard visual generado', 'KPIs principales', 'Graficos', 'Tablas', 'Insights', 'Recomendaciones', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 5,
    isActive: false,
    accentColor: '#7c3aed',
    icon: 'BrainCircuit',
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
  },
  {
    id: 'spend_analysis',
    agentKey: 'spend_analysis',
    slug: 'analisis-gastos',
    name: 'Analisis de Gastos',
    description: 'Analiza gastos por proveedor, categoria, centro de costo, periodo o area para detectar concentracion, variaciones, oportunidades de ahorro y riesgos.',
    longDescription: 'Agrupa datos de gasto y prioriza oportunidades de ahorro, proveedores criticos y variaciones relevantes.',
    category: 'Finanzas',
    automationType: 'Analitica',
    useCase: 'Explorar gasto por proveedor, categoria o periodo para priorizar negociaciones.',
    functionalities: ['Lee Excel/CSV de gastos', 'Agrupa por proveedor, categoria y periodo', 'Detecta top gastos', 'Detecta variaciones', 'Sugiere oportunidades de ahorro'],
    benefits: ['Mejora control del gasto', 'Identifica proveedores criticos', 'Ayuda a priorizar negociaciones'],
    inputs: ['Archivo Excel/CSV de gastos', 'Periodo', 'Categoria', 'Centro de costo'],
    outputs: ['Resumen de gastos', 'Top proveedores', 'Top categorias', 'Variaciones', 'Alertas', 'Recomendaciones', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 6,
    isActive: false,
    accentColor: '#be185d',
    icon: 'TrendingUp',
    createdAt: '2026-04-06T00:00:00.000Z',
    updatedAt: '2026-04-06T00:00:00.000Z',
  },
  {
    id: 'contract_risk_analysis',
    agentKey: 'contract_risk_analysis',
    slug: 'analisis-contratos-riesgos',
    name: 'Analisis de Contratos y Deteccion de Riesgos',
    description: 'Analiza contratos de proveedores para detectar clausulas criticas, riesgos, obligaciones, penalidades, vencimientos, renovaciones y puntos de negociacion.',
    longDescription: 'Resume obligaciones contractuales y prioriza alertas para que compras pueda revisar riesgos antes de firmar o renovar.',
    category: 'Contratos',
    automationType: 'Riesgo',
    useCase: 'Revisar contratos de proveedores y levantar puntos criticos de negociacion.',
    functionalities: ['Lee contratos PDF/DOCX', 'Resume obligaciones', 'Detecta riesgos', 'Identifica clausulas criticas', 'Detecta penalidades y vencimientos'],
    benefits: ['Reduce riesgo contractual', 'Mejora revision previa a firma', 'Ayuda a compradores no legales a detectar alertas'],
    inputs: ['Contrato o anexos', 'Contexto de compra', 'Puntos de preocupacion'],
    outputs: ['Resumen contractual', 'Matriz de riesgos', 'Clausulas criticas', 'Obligaciones', 'Recomendaciones', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 7,
    isActive: false,
    accentColor: '#dc2626',
    icon: 'TriangleAlert',
    createdAt: '2026-04-07T00:00:00.000Z',
    updatedAt: '2026-04-07T00:00:00.000Z',
  },
  {
    id: 'supplier_evaluation_ranking',
    agentKey: 'supplier_evaluation_ranking',
    slug: 'evaluacion-ranking-proveedores',
    name: 'Evaluacion y Ranking de Proveedores',
    description: 'Evalua proveedores segun criterios tecnicos, comerciales, cumplimiento, experiencia, documentacion, desempeno y riesgo para generar ranking y recomendacion.',
    longDescription: 'Estandariza la evaluacion de proveedores con criterios, pesos, score, riesgos y documentacion faltante.',
    category: 'Proveedores',
    automationType: 'Evaluacion',
    useCase: 'Seleccionar proveedores con un ranking sustentado y comparable.',
    functionalities: ['Evalua informacion de proveedores', 'Genera criterios y pesos', 'Califica proveedores', 'Detecta documentacion faltante', 'Genera ranking'],
    benefits: ['Mejora seleccion de proveedores', 'Reduce decisiones subjetivas', 'Estandariza evaluacion'],
    inputs: ['Informacion de proveedores', 'Criterios de evaluacion', 'Pesos', 'Documentacion'],
    outputs: ['Score por proveedor', 'Ranking', 'Fortalezas', 'Riesgos', 'Documentacion faltante', 'Recomendacion', 'PDF descargable'],
    status: 'coming_soon',
    visibleToBuyer: true,
    sortOrder: 8,
    isActive: false,
    accentColor: '#64748b',
    icon: 'ShieldCheck',
    createdAt: '2026-04-08T00:00:00.000Z',
    updatedAt: '2026-04-08T00:00:00.000Z',
  },
];
